### ISSUE TITLE
Caching broken because ES6 maps can't be converted to JSON?

### ISSUE THREAD

**Issue by robbiet480** [cubehouse/themeparks#105]
I've been having this weird issue when caching is enabled. Without changing any code, just using the example caching setup _with_ an external cache module such as one of the Redis modules or the memory store, I get this error: `TypeError: this[s_scheduleDates].has is not a function` from [this line](https://github.com/cubehouse/themeparks/blob/master/lib/schedule.js#L297) because `this[s_scheduleDates]` is just an empty object and not a `Map` which would have `.has`. Investigating further shows me that the cache only has values like `{"dates":{},"datesSpecial":{}}` for the `openingtimes` key. I then quickly realized that the `toJSON` function doesn't appear to be converting the `Map`s to values that can actually be stored as JSON. Adding an extra JSON.stringify in park.js around the `this[s_scheduleData].toJSON()` call doesn't change the situation.

So not sure how to fix this without removing the `Map` or implementing some kind of crazy JSON mapper. But the original issue stems from the cache not having proper data because a `Map` can't be serialized as JSON, even with `toJSON()` in the mix.

BTW, i'm only trying to get wait times. It appears that opening times are gotten before wait times since #42 was implemented.

EDIT: Just checked the v5 branch, I see you will be removing caching in favor of required SQLite storage. Firstly, I hope that the impending v5 doesn't mean that this issue won't get fixed because while I don't have an issue with SQLite generally, it's not going to work well for my server environment, Google Cloud Functions, as you can't store files long term on the disk. I don't think it makes sense to have to store the SQLite database on something like Cloud Storage either. Hopefully you are using a generic DB adapter so something like Postgres or MySQL could be dropped in. Anyway, just my two cents on that matter.

**Comment by cubehouse** [comment]
Interesting issue, the main issue with the current caching implementation is that you are the first person I have ever encountered to be using it. I read over any project I find using the library to try and understand how it's being used, and it's just not being setup anywhere, so it really hasn't had the attention it's needed to be robust enough. I can try and look into this soon though when I get a moment.

Regarding the v5 branch, the Disney World API has now completely changed, and now relies on having a permanent storage to keep a history of data diffs which are updated via real-time long-polling. In order to avoid users having to supply their own databases for caching (because nobody has been so far), I've opted to defaulting to SQLite by-default. If caching isn't used, I fear this project is going to start sucking up way too much bandwidth for park API servers, which I want to avoid at all costs, as I want to remain on good terms with all park companies.
This kind of feedback is exactly what I want now before I steam ahead with v5, so I will see what I can do. I suspect I will require SQLite out-of-the-box, but I don't think it would be too hard to offer optional different bindings for other standard SQL-like databases.

**Comment by robbiet480** [comment]
Would love to chat more in depth with you about my use case and recent findings regarding the API. I think it would be helpful to you for shaping v5. Feel free to shoot me an email if you're interested, it's on my GitHub profile.

**Comment by Vortec4800** [comment]
Has there been any movement on this? I just set up the API with caching enabled, and am also running into this same error in ES6.

**Comment by cubehouse** [comment]
Hi, work on this is being done in the 5.0 branch, which is a large rewrite of the core framework. 

Please give it a spin and see if it works for you. It's still WIP, but I have uploaded a few versions with a beta tag to npm.

**Comment by Vortec4800** [comment]
Okay thanks for the update. Let me finish the primary development I'm doing on the current stable version, then once I know things are working (without caching) I can try the new beta and see how it does.
