### ISSUE TITLE
fastPassReturnTime and Schedule disappear when outputing json file

### ISSUE THREAD

**Issue by bluesolarflare** [cubehouse/themeparks#109]
I seem to be having an issue when trying to write the current wait times for a park to a .json file.

The code I have is as follows:

`var Themeparks = require("themeparks");
var fs = require("fs");
var disneyMagicKingdom = new Themeparks.Parks.DisneylandResortMagicKingdom();

disneyMagicKingdom.GetWaitTimes().then(function(rides) {
var disneyland = JSON.stringify(rides);

   fs.writeFile('c:\temp\disneyland.json', disneyland, function(err){
    if(err) throw err;
  })
})
`

Sometimes when I run it with node.js it will output just fine, however there are instances, where it simply seems to strip away the fastPassReturnTime and Schedule subobjects of the json.  Any help would be appreciated.  Thanks.

**Comment by cubehouse** [comment]
Hi,

Did you ever resolve this issue?

Looking at your code, I see you're not keeping your DisneylandResortMagicKingdom around. Are you manually calling your NodeJS script on a timer or something? I'd recommend leaving the script running and setup a timer within NodeJS so that you don't recreate the DisneylandResortMagicKingdom object every time you request times.
I suspect there may be a timing issue where the schedule data isn't fetched yet, where not calling the script fresh all the time will likely sidestep.
