### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by LelieJens** [cubehouse/themeparks#127]
Hello, 

Currently I'm working on something using your amazing API, thank you so much. Although I have a few questions: 

-  What happens if a ride is closed due to a technical problem, how will this affect the waiting time parameter? Will it display 0 or return something else?
- Specifically for Europa-Park: Do you know the interval the times change? I have checked by counting etc, and it could be 5 minutes, but maybe you know the exact time. 
- Where did you get the names from the rides of Europa-Park? Some are translated to English and some aren't, which makes it quite confusing. 
- Is it possible to add opening and closing times from Europa-Park to the API?

Thank you so much!

**Comment by cubehouse** [comment]
Hi,

- Rides which are closed will have a 0 wait time, but their status will no longer be Operating. Please see the README for the other options it could be
- I do not know the interval times change, I would never recommend checking more than every 5 minutes anyway, otherwise parks may block your requests for hitting their servers too often
- Europe Park ride names are fetched from their pointsofinterest API, see https://github.com/cubehouse/themeparks/blob/master/lib/europapark/index.js
- Park opening and closing times should already be available through the GetOpeningTimes()
