### ISSUE TITLE
Question about API URLs for Park Hours (Disney World)

### ISSUE THREAD

**Issue by kennonb** [cubehouse/themeparks#131]
Hi,

This package looks great, but I have a few small use-case that I'm trying to implement, so I'm thinking of just using my own Access Token function with a quick PHP helper to fetch the data points I need.

All that said, I was able to get the wait times easily for Disney World, but I'm having trouble with fetching Park Hours.

When I looked at the code, this is the URL that it looked like it would fetch, but I'm getting a `QUERYSTRING_INVALID` error (220029):

`https://api.wdpro.disney.go.com/mobile-service/public/ancestor-activities-schedules/80007944;entityType=destination`

Is it possible that I'm just overlooking something simple here?

Thanks for any help!

**Comment by kennonb** [comment]
Ok, I found a URL that works for retrieving these when I was looking through the wait times response. I'm going to close this, but if anyone else is interested, it looks like it follows this pattern:

`https://api.wdpro.disney.go.com/global-pool-override-A/facility-service/schedules/{$parkID}?region=us`

**Comment by cubehouse** [comment]
Hi,

I'm glad you solved your issue :) for reference, this method of fetching calendar information will likely be deprecated in future, as Disney are using a new live database API for the current app (see the 5 branch for the implementation).

Generally, I'm afraid I cannot support assisting with other implementations of this library, and definitely not in other languages, as the codebase requires changes constantly to keep working, and I would ideally like people to help maintain this library (it is open source!) together rather than spread the same quickly out-of-date code into other projects.

**Comment by kennonb** [comment]
Thanks. I understand. I didn't realize their endpoints were changing so rapidly.

I'll try to get the library working again in the near future so I can contribute, but I wasn't having any luck with the master branch. I kept having npm tell me that there were required libs that weren't installed, but even after installing it still wouldn't compile.

Anyway, I'll take another look at it another day.
