### ISSUE TITLE
Support for Walt Disney World Fastpass+ Available Times

### ISSUE THREAD

**Issue by jschlegel** [cubehouse/themeparks#134]
When Fastpasses are available for an attraction at Walt Disney World, the API does not supply the available times.  It would be helpful to be able to obtain an array of available fastpass times or at least the first available fastpass window for Walt Disney World attractions that have Fastpass+.

**Comment by DougSisk** [comment]
Because WDW is FastPass+ and not FastPass, it's a separate API that's not alongside wait times. Unlike the wait time API which is public, this one requires a Disney account that has WDW tickets linked to it.

**Comment by cubehouse** [comment]
Hi,

As Doug says, this is more complex than getting wait times as you need a WDW account with a valid ticket for that day. Because of this, I'm afraid this is beyond the scope of the project.

I reckon you could use this library as a base and use the API call methods to set this up yourself (using the library mainly for handling the authentication) - but I'm afraid I won't be able to help you with that.
