### ISSUE TITLE
Guidelines to help in the project - fireworks schedule

### ISSUE THREAD

**Issue by eduardo-veras** [cubehouse/themeparks#274]
Hello there!

I like to ask for directions before making a PR.  :)

I read the Wiki's about "contributions" and "adding new parks", but it was not clear in on point:

Is it OK to send a new PR with the information being collected by a web scrapping, and not from an API?

I have a system that collects fireworks schedule for Disney parks in Orlando from [DIS Website](https://www.wdwinfo.com/wdwinfo/hours.htm). And it's been reliable in the last 12 months. 

This is something worth to include in the project along with the other Disney's park information?

**Comment by cubehouse** [comment]
Hi, thanks for your question.

People have asked for similar things in the past, but I feel it is too far beyond the scope of this library, since it already takes a lot of effort to maintain the wait times and park opening hours as it is - and I don't want to implement any core features unless they are generally supported for all parks.

I'm starting to think about version 6.0 and the future of this library, so this may be something that appears in that plan, but only if the library changes shape significantly. The more features for all parks we add, the more tiny little updates I need to push out, which is getting silly. So it might be that the library becomes a hosted API somewhere, which would allow for these sorts of things.
