### ISSUE TITLE
Ride status and wait times not working for Merlin parks

### ISSUE THREAD

**Issue by lightswitchr** [cubehouse/themeparks#63]
I've checked this with Alton Towers and Chessington:

* [Alton Towers](http://ridetimes.co.uk) - themeparks says all rides are shut.
* [Chessington](https://www.chessington.com/plan/today-at-chessington.aspx) - themeparks also says all rides are shut.

Both parks are open and operating.

**Comment by cubehouse** [comment]
Hmm, the API must have changed in some way. If it's still returning some sort of data, I guess they've either moved to a whole new system, or they've just bumped the API version number.

I'll check it out when I get a moment.

**Comment by cubehouse** [comment]
Bit baffling. Updated the Alton Towers app on a device and it's now accessing wait times through two different APIs:
* http://ridetimes.co.uk/queue-times-new.php
* https://api.attractions.io/v1/live-data

The latter does all sorts of nonsense with registering the device ID and using that to authenticate in order to get the wait times, which is quite a change from the existing API from before.

I can look into updating the library, but it won't be for a few days before I get the chance to do it properly.

Looks like Chessington is still using the same legacy API, but the server may have changed slightly. I'm looking at a new key in the body I've not seen before called "session" that might be triggering no data being returned? Hard to say until I get a chance to test this during park operating hours.

Happy to look over any pull requests if anyone wants a crack at it. I think we're going to have to split Alton Towers and Chessington into separate frameworks (and create a new entry for Thorpe Park! I see it has an app now using the new attractions.io API).

**Comment by cubehouse** [comment]
Working on getting Alton Towers (+now Thorpe Park!) working again, progress on this branch:
https://github.com/cubehouse/themeparks/tree/merlinparks

Hopefully get finished in next few days!

**Comment by cubehouse** [comment]
That was much faster to fix than I thought once I got the groundwork in...

Should now be fixed in 4.1.6. Let me know how it goes.

**Comment by lightswitchr** [comment]
Awesome! Well done
