### ISSUE TITLE
Add Typhoon Lagoon, Wide World of Sports, Blizzard Beach, Disney Springs

### ISSUE THREAD

**Issue by primedime** [cubehouse/themeparks#84]
I would be willing to help add these parks however I am having a hard time finding the URLs for the data.

I see they have open/close times here: https://disneyworld.disney.go.com/calendars/park-hours/

How can I get the needed URLs to work on adding these to the project? I assume I can add them based on the current Disney Parks?

**Comment by cubehouse** [comment]
Thanks for your question. Aside from the two water parks, those areas don't offer wait times (and the water parks used to return pretty random data, so I've not considered them very useful in then past), so I don't think they'll ever become a "core part" of the library.

However, the library is pretty flexible, so it is possible to quite easily extend it locally and make it do all sorts of weird things.

Because the water parks and the "entertainment areas" are categorised differently in the APIs to the theme parks, I've pushed a minor library update out (4.6.3) which adds a required change for this to work.
I've also created an example file showing you how to make a set of new park objects that will give you the opening times for the requested areas the same as the rest of the library works :)

https://gist.github.com/cubehouse/37706288d51423ffe0664d8795bb02d4

The main trick is just finding the right park IDs, which you can find with enough will-power by watching the APIs.

Hope this helps!
