### ISSUE TITLE
Querying the API on an Angular app (client-side)

### ISSUE THREAD

**Issue by christopherkade** [cubehouse/themeparks#90]
I had previously developed a web app to simply display wait-times using a small node server, I wish to rewrite this app statically by doing all the `themepark` API calls client-side, would that be possible? If not, why?

Thank you for your work 🥇

**Comment by cubehouse** [comment]
Hi,

It is theoretically possible to do this entirely client-side, largely the issues come down to:

* HTTP library - this library currently uses needle, which is a fantastic lightweight HTTP lib for making HTTP requests. You would need a browser-compatible HTTP library that will support all the unusual methods of making API requests with authentication, headers etc. to make this work with Angular. Specifically, you will often need to be able to rewrite the User-Agent header when making requests, which I'm not sure if all browsers support doing this?
* Performance - Often to get a list of ride names and their wait times you need to make multiple API requests that fetch data-sets containing literally everything in the park. By doing this server-side, you can cache these huge data-sets and save the client from having to ever fetch 3-4MB requests at all. You would have to rewrite and handle all of this client-side (caching data as you go) if you wanted to do this in Angular. Much like how the official apps work (at this point you're largely just re-writing the official app). From an end-user perspective, I think it's nicer to request a pre-cached set of wait times from a server, rather than making their client do all the bells and whistles to fetch everything needed to then only extract a small-subset of the data for themselves.

Generally it is totally possible, but it is not something this library would ever implement as it requires a lot more framework-specific work to implement correct caching and network requests. You would also lose functionality such as wait-time history, which is very powerful.

If you're only interested in implementing a single park, I would investigate if you can reproduce the authentication in the browser first, and start building from there.
