### ISSUE TITLE
How to retrieve items without getting everything

### ISSUE THREAD

**Issue by AmrineA** [cubehouse/themeparks#91]
We've been playing around with this a little bit, but have run into a list of things we'd like to do, might be possible, but doesn't appear to work or we don't know how to do it.

- Get a list of rides without wait times
- Pull a wait time for one specific ride, we tried using the GetRideObject and passed in a variety of IDs, but it kept coming back null
- Pull opening times for a specific date without pulling them all

**Comment by cubehouse** [comment]
Heya,

Sorry for the delay in replying! Been a little busy in Anaheim, and just gotten back to sorting out emails and such.

Generally those things are not currently possible with the library, the functions available are in the main README. The main focus for the library at the moment is to do a few things well for as many parks as possible. I hope as the project grows we can start to add features such as this, as we start to get more contributors.

Pretty much every park API returns all parks or all opening times together at once, so generally if we were to add ride-specific wait times or date-specific opening time API calls, we'd literally just be calling the normal function, and then looping over the result to find the one we want. Because of this, I would recommend just doing this outside the library in your project.

Getting ride names is an interesting one. A lot of parks return the names of "things", and it's hard to decipher which are rides and not toilets/restaurants/first-aid etc. until you've actually fetched some wait times to associate names with rides.

**Comment by AmrineA** [comment]
Thanks for the update. I kind of figured this might be the case but wanted
to ask.

On Dec 21, 2017 3:44 PM, "James Holding" <notifications@github.com> wrote:

Heya,

Sorry for the delay in replying! Been a little busy in Anaheim, and just
gotten back to sorting out emails and such.

Generally those things are not currently possible with the library, the
functions available are in the main README. The main focus for the library
at the moment is to do a few things well for as many parks as possible. I
hope as the project grows we can start to add features such as this, as we
start to get more contributors.

Pretty much every park API returns all parks or all opening times together
at once, so generally if we were to add ride-specific wait times or
date-specific opening time API calls, we'd literally just be calling the
normal function, and then looping over the result to find the one we want.
Because of this, I would recommend just doing this outside the library in
your project.

Getting ride names is an interesting one. A lot of parks return the names
of "things", and it's hard to decipher which are rides and not
toilets/restaurants/first-aid etc. until you've actually fetched some wait
times to associate names with rides.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cubehouse/themeparks/issues/91#issuecomment-353453330>,
or mute the thread
